### ISSUE TITLE
Add evolution information

### ISSUE THREAD

**Issue by aqua-d** [kikisaints/GalarPokedexTracker#1]
Please include the “forward” and “backward” evolution information. 

Suppose Pokémon evolves at level 14. 

For the pre evolution Pokémon, I want to know that it evolves at 14.

For the post evolution Pokémon, I want to know that it would have evolved earlier at level 14.

Also, when I select one Pokémon, you know how there’s the drop down? It would be awesome to also include the other Pokémon in the evolution chain.

**Comment by aqua-d** [comment]
Just noticed that normal type is missing in the grouping for the green triangle. See eg 338 - normal has no effect. Maybe there should be a different symbol for the no effect category? Whatever is easiest. I’m guessing it is because it is pulling the 0.5 multiplier but not also the 0 multiplier. Just a guess. Good luck. Thanks.

**Comment by kikisaints** [comment]
Thanks for logging an issue @aqua-d - I'm currently working your feature request of adding an evolution chain.

Here's a preview of that:
![IMG_0914](https://user-images.githubusercontent.com/6964369/73892150-eff72800-482a-11ea-8f94-cdbd58e4b517.PNG)

But you are correct with the type-match up multipliers. I'm not accounting for no effect types. I'll add that in the coming release as well - probably a no effect indicator as you've suggested.

**Comment by kikisaints** [comment]
Closing this out, because as of the most recent update this should be in.
